#!/bin/sh

set -e
set -x

mkdir -p cert
chmod 700 cert
# Generate private key with password "password"
openssl genrsa -aes128 -passout pass:password -out cert/server.pem 2048
# Remove password from private key
openssl rsa -passin pass:password -in cert/server.pem -out cert/server.pem
# Generate CSR (make sure the common name CN field matches your server
# address. It's set to "localhost" here.)
openssl req -new -key cert/server.pem -out cert/server.csr -subj '/C=US/ST=California/L=Everywhere/CN=localhost'
# Sign the CSR and create certificate
openssl x509 -req -days 365 -in cert/server.csr -signkey cert/server.pem -out cert/server.crt
# Clean up
rm cert/server.csr
chmod 600 cert/*
